remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: HOAXSHELL X ATTINY 85 
description: Convierte tu Digispark ATtiny85 en un USB que lanza una reverse shell usando Hoaxshell
